import type { McpServer, WeeklyReport } from "./types";

export const servers: McpServer[] = [
  {
    slug: "github-mcp-server",
    name: "GitHub MCP Server",
    category: "Developer tools",
    tagline: "Repository, issue, pull request, and code search workflows for agentic coding.",
    source: "Official MCP registry, GitHub search",
    packageName: "github/github-mcp-server",
    installCommand: "docker run -i --rm ghcr.io/github/github-mcp-server",
    repositoryUrl: "https://github.com/github/github-mcp-server",
    stars: 24700,
    lastReviewed: "2026-05-09",
    transports: ["stdio", "streamable-http"],
    clients: ["claude", "cursor", "codex", "vscode"],
    risk: "low",
    score: {
      installDocs: 91,
      maintenance: 94,
      auth: 88,
      compatibility: 93,
      usefulness: 96,
      safety: 86,
    },
    signals: [
      "First-party publisher",
      "Active issue and release activity",
      "Clear token scope guidance",
      "High-value daily developer workflow",
    ],
    evidence: [
      "Installation path is documented for Docker and local clients.",
      "OAuth and token handling are explicit enough to review before install.",
      "Common workflows map cleanly to code review and issue triage use cases.",
    ],
    cautions: [
      "Teams should pin allowed repository scopes before enabling write actions.",
      "Review organization policy for issue and pull-request mutation tools.",
    ],
    examples: [
      "Summarize open pull requests before standup.",
      "Find recent issues related to a failing CI workflow.",
      "Create a draft issue from a debugging transcript.",
    ],
  },
  {
    slug: "filesystem",
    name: "Filesystem",
    category: "Local automation",
    tagline: "Controlled local file access for assistants running in a developer workspace.",
    source: "Official MCP examples, client docs",
    packageName: "@modelcontextprotocol/server-filesystem",
    installCommand: "npx -y @modelcontextprotocol/server-filesystem ./workspace",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex", "vscode"],
    risk: "medium",
    score: {
      installDocs: 86,
      maintenance: 82,
      auth: 72,
      compatibility: 92,
      usefulness: 89,
      safety: 71,
    },
    signals: [
      "Broad client support",
      "Simple install path",
      "Powerful local access surface",
      "Needs tight path scoping",
    ],
    evidence: [
      "The server is easy to install and widely referenced in client setup guides.",
      "Usefulness is high for local coding agents and document workflows.",
      "Risk depends heavily on the root directories exposed to the MCP client.",
    ],
    cautions: [
      "Never expose home directories or secrets folders by default.",
      "Prefer read-only or workspace-scoped configurations when possible.",
    ],
    examples: [
      "Read a project README before editing.",
      "List generated artifacts after a build.",
      "Inspect a local configuration file with explicit user approval.",
    ],
  },
  {
    slug: "postgres",
    name: "Postgres",
    category: "Databases",
    tagline: "SQL inspection and query workflows for Postgres-backed products.",
    source: "Official MCP examples, Smithery, GitHub search",
    packageName: "@modelcontextprotocol/server-postgres",
    installCommand: "npx -y @modelcontextprotocol/server-postgres postgresql://...",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: {
      installDocs: 80,
      maintenance: 79,
      auth: 68,
      compatibility: 84,
      usefulness: 87,
      safety: 66,
    },
    signals: [
      "Strong analytical value",
      "Credential handling is deployment-specific",
      "Readonly roles strongly recommended",
      "Can expose sensitive production data",
    ],
    evidence: [
      "The install path is straightforward for teams already using connection strings.",
      "Quality depends on database role scoping and environment separation.",
      "Useful for schema exploration, query drafting, and product analytics.",
    ],
    cautions: [
      "Use a readonly role and replica where practical.",
      "Do not give agent sessions access to production write credentials.",
    ],
    examples: [
      "Explain table relationships before building a feature.",
      "Draft a read-only analytics query.",
      "Find columns likely to contain customer-identifying data.",
    ],
  },
  {
    slug: "context7",
    name: "Context7",
    category: "Documentation",
    tagline: "Library documentation retrieval for coding assistants.",
    source: "Smithery, GitHub search, community mentions",
    packageName: "@upstash/context7-mcp",
    installCommand: "npx -y @upstash/context7-mcp",
    repositoryUrl: "https://github.com/upstash/context7",
    stars: 15800,
    lastReviewed: "2026-05-09",
    transports: ["stdio", "sse"],
    clients: ["claude", "cursor", "codex"],
    risk: "low",
    score: {
      installDocs: 88,
      maintenance: 90,
      auth: 84,
      compatibility: 82,
      usefulness: 91,
      safety: 83,
    },
    signals: [
      "Clear developer use case",
      "Low data sensitivity by default",
      "High community visibility",
      "Good fit for coding-agent workflows",
    ],
    evidence: [
      "The value proposition is narrow and easy to validate during install tests.",
      "Documentation retrieval does not require broad local or account privileges.",
      "Community mentions show recurring usage in coding-assistant setup guides.",
    ],
    cautions: [
      "Check source freshness for fast-moving frameworks.",
      "Teams with private docs still need a separate access review.",
    ],
    examples: [
      "Fetch current framework docs while editing a component.",
      "Compare API signatures across package versions.",
      "Reduce hallucinated library usage in code generation.",
    ],
  },
  {
    slug: "slack-mcp",
    name: "Slack MCP Server",
    category: "Collaboration",
    tagline: "Channel search, message context, and reply drafting for team workflows.",
    source: "Smithery, Glama, GitHub search",
    packageName: "@modelcontextprotocol/server-slack",
    installCommand: "npx -y @modelcontextprotocol/server-slack",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "high",
    score: {
      installDocs: 74,
      maintenance: 78,
      auth: 61,
      compatibility: 76,
      usefulness: 82,
      safety: 58,
    },
    signals: [
      "Useful operational context",
      "Sensitive workspace data surface",
      "OAuth scopes must be inspected",
      "Write actions require policy controls",
    ],
    evidence: [
      "The workflow value is clear for incident review and team memory.",
      "Security score is lower until OAuth scopes and retention handling are reviewed.",
      "Best used with channel allowlists and read/write separation.",
    ],
    cautions: [
      "Avoid broad workspace read scopes for default installs.",
      "Require user confirmation before posting or editing messages.",
    ],
    examples: [
      "Summarize a project channel for a daily digest.",
      "Find recent messages about a production incident.",
      "Draft a reply using thread context.",
    ],
  },
  {
    slug: "notion-mcp",
    name: "Notion MCP Server",
    category: "Productivity",
    tagline: "Workspace search and page operations for Notion-backed team memory.",
    source: "Smithery, GitHub search, community mentions",
    packageName: "@notionhq/notion-mcp-server",
    installCommand: "npx -y @notionhq/notion-mcp-server",
    repositoryUrl: "https://github.com/makenotion/notion-mcp-server",
    stars: 8200,
    lastReviewed: "2026-05-09",
    transports: ["stdio", "streamable-http"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: {
      installDocs: 84,
      maintenance: 86,
      auth: 74,
      compatibility: 80,
      usefulness: 88,
      safety: 70,
    },
    signals: [
      "Strong workspace knowledge use case",
      "OAuth scopes require admin review",
      "Good fit for read-heavy retrieval",
      "Write actions should be gated",
    ],
    evidence: [
      "Useful for finding project docs, specs, and operational notes.",
      "Risk level depends on workspace scope and page permission boundaries.",
      "Installation path is clear enough for a manual team review.",
    ],
    cautions: [
      "Avoid broad workspace access during early trials.",
      "Separate read-only retrieval from page mutation workflows.",
    ],
    examples: [
      "Find the latest product requirements doc.",
      "Summarize project decisions from a workspace section.",
      "Draft a page update after a release review.",
    ],
  },
  {
    slug: "browserbase",
    name: "Browserbase",
    category: "Web automation",
    tagline: "Hosted browser sessions for agents that need controlled web interaction.",
    source: "Smithery, GitHub search, npm package metadata",
    packageName: "@browserbasehq/mcp-server-browserbase",
    installCommand: "npx -y @browserbasehq/mcp-server-browserbase",
    repositoryUrl: "https://github.com/browserbase/mcp-server-browserbase",
    stars: 3100,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: {
      installDocs: 82,
      maintenance: 85,
      auth: 76,
      compatibility: 78,
      usefulness: 86,
      safety: 69,
    },
    signals: [
      "High leverage for web QA",
      "External account credentials required",
      "Session recording can improve auditability",
      "Automation scope needs policy limits",
    ],
    evidence: [
      "Useful for QA, extraction, and browser-state workflows.",
      "Account and API-key handling must be reviewed before team rollout.",
      "Best value appears when paired with reproducible tests.",
    ],
    cautions: [
      "Do not allow unattended access to authenticated production apps.",
      "Store session artifacts according to team data policy.",
    ],
    examples: [
      "Validate a deployed signup flow.",
      "Capture a screenshot during incident triage.",
      "Check a docs page for broken interactive states.",
    ],
  },
  {
    slug: "stripe-mcp",
    name: "Stripe MCP Server",
    category: "Finance",
    tagline: "Payment object lookup and billing operations for Stripe-backed products.",
    source: "Official docs, Smithery, GitHub search",
    packageName: "@stripe/mcp",
    installCommand: "npx -y @stripe/mcp",
    repositoryUrl: "https://github.com/stripe/agent-toolkit",
    stars: 5400,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "high",
    score: {
      installDocs: 83,
      maintenance: 87,
      auth: 64,
      compatibility: 72,
      usefulness: 84,
      safety: 55,
    },
    signals: [
      "Financial data access",
      "Strong operational usefulness",
      "API key scopes must be locked down",
      "Write actions require explicit approvals",
    ],
    evidence: [
      "Useful for payment debugging and billing support workflows.",
      "Safety score is constrained by sensitive financial data exposure.",
      "Teams should review restricted key scopes before enabling tools.",
    ],
    cautions: [
      "Use restricted keys and sandbox mode for evaluation.",
      "Never allow autonomous refund, subscription, or invoice mutation without approval.",
    ],
    examples: [
      "Look up a failed payment by customer context.",
      "Explain a subscription state during support triage.",
      "Draft a safe billing investigation checklist.",
    ],
  },
  {
    slug: "brave-search",
    name: "Brave Search",
    category: "Search",
    tagline: "Web search results for agents that need current public context.",
    source: "Official MCP examples, Smithery, package metadata",
    packageName: "@modelcontextprotocol/server-brave-search",
    installCommand: "npx -y @modelcontextprotocol/server-brave-search",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex", "vscode"],
    risk: "low",
    score: {
      installDocs: 79,
      maintenance: 78,
      auth: 80,
      compatibility: 88,
      usefulness: 81,
      safety: 78,
    },
    signals: [
      "Low local data exposure",
      "External API key required",
      "Broad client compatibility",
      "Useful for current public references",
    ],
    evidence: [
      "The server has a narrow public-search surface.",
      "Risk mostly comes from query logging and API-key handling.",
      "Useful when agents need current public information.",
    ],
    cautions: [
      "Do not send private customer data as search queries.",
      "Review provider logging and retention terms.",
    ],
    examples: [
      "Find current package docs.",
      "Check whether a CVE affects a dependency.",
      "Gather public references for a market scan.",
    ],
  },
  {
    slug: "memory",
    name: "Memory",
    category: "Local automation",
    tagline: "Persistent local knowledge graph for assistant context across sessions.",
    source: "Official MCP examples, client docs",
    packageName: "@modelcontextprotocol/server-memory",
    installCommand: "npx -y @modelcontextprotocol/server-memory",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: {
      installDocs: 77,
      maintenance: 78,
      auth: 70,
      compatibility: 81,
      usefulness: 79,
      safety: 64,
    },
    signals: [
      "Persistent data surface",
      "Useful for long-running workflows",
      "Needs retention controls",
      "Low external attack surface by default",
    ],
    evidence: [
      "Persistence can improve continuity for repeated tasks.",
      "Safety depends on what the assistant writes into memory.",
      "Best used with clear retention and deletion controls.",
    ],
    cautions: [
      "Avoid storing secrets or personal data in memory entries.",
      "Give users clear controls to inspect and delete stored facts.",
    ],
    examples: [
      "Remember repository conventions across sessions.",
      "Track project-specific terminology.",
      "Store reusable non-sensitive workflow notes.",
    ],
  },
];

export const weeklyReports: WeeklyReport[] = [
  {
    slug: "weekly-best-mcp-service",
    title: "Best MCP Server This Week",
    weekOf: "2026-05-09",
    winnerSlug: "github-mcp-server",
    summary:
      "GitHub MCP Server leads this first manual review because it combines a high-utility developer workflow with first-party maintenance signals and a security posture teams can reason about before install.",
    whyItWon: [
      "Clear install path and strong first-party ownership.",
      "Practical value shows up immediately in code review, issue triage, and repository search.",
      "Auth risk is manageable when teams pin scopes and separate read from write actions.",
    ],
    watchList: [
      "Filesystem remains essential, but its trust score depends on path scoping.",
      "Context7 is a strong low-risk documentation candidate for coding teams.",
      "Slack is useful but needs deeper OAuth and workspace-retention review before recommendation.",
    ],
  },
];
