import { overallScore } from "./scoring";
import type { ClientKey, ConfidenceLevel, McpServer, ReviewStatus, RiskLevel, SourceLink, WeeklyReport } from "./types";

const registryLink: SourceLink = {
  label: "Official MCP registry",
  type: "registry",
  url: "https://registry.modelcontextprotocol.io/",
};

type ServerSeed = Omit<McpServer, "description" | "evidenceUpdated" | "maintainerVerified" | "trustScore"> & {
  description?: string;
  evidenceUpdated?: string;
  maintainerVerified?: boolean;
};

function server(seed: ServerSeed): McpServer {
  return {
    ...seed,
    description: seed.description ?? seed.tagline,
    evidenceUpdated: seed.evidenceUpdated ?? seed.lastReviewed,
    maintainerVerified: seed.maintainerVerified ?? seed.status === "maintainer_verified",
    trustScore: overallScore(seed.score),
  };
}

const clients: ClientKey[] = ["claude", "cursor", "codex", "vscode"];

function score(base: number) {
  return {
    installDocs: base,
    maintenance: Math.max(0, base - 2),
    auth: Math.max(0, base - 8),
    compatibility: Math.min(100, base + 3),
    usefulness: Math.min(100, base + 5),
    safety: Math.max(0, base - 6),
  };
}

function repo(url: string): SourceLink {
  return { label: "GitHub repo", type: "repository", url };
}

function docs(url: string): SourceLink {
  return { label: "Official docs", type: "docs", url };
}

function npmPackage(name: string): SourceLink {
  return { label: "NPM package", type: "package", url: `https://www.npmjs.com/package/${name}` };
}

const reviewedServers: McpServer[] = [
  server({
    slug: "github-mcp-server",
    name: "GitHub MCP Server",
    category: "Developer tools",
    tagline: "Repository, issue, pull request, and code search workflows for agentic coding.",
    source: "Official MCP registry, GitHub repository, package documentation",
    sourceLinks: [
      repo("https://github.com/github/github-mcp-server"),
      docs("https://docs.github.com/en/copilot/how-tos/provide-context/use-mcp/use-the-github-mcp-server"),
      { label: "GitHub package registry", type: "package", url: "https://github.com/github/github-mcp-server/pkgs/container/github-mcp-server" },
      registryLink,
    ],
    packageName: "ghcr.io/github/github-mcp-server",
    installCommand: "docker run -i --rm ghcr.io/github/github-mcp-server",
    repositoryUrl: "https://github.com/github/github-mcp-server",
    stars: 24700,
    lastReviewed: "2026-05-14",
    evidenceUpdated: "2026-05-14",
    status: "maintainer_verified",
    confidence: "high",
    maintainerVerifiedAt: "2026-05-14",
    transports: ["stdio", "streamable-http"],
    clients,
    risk: "low",
    score: { installDocs: 94, maintenance: 96, auth: 90, compatibility: 94, usefulness: 97, safety: 88 },
    signals: ["First-party publisher", "Active maintenance", "Clear token-scope model", "High daily developer usefulness"],
    evidence: [
      "First-party GitHub ownership materially improves provenance and maintenance confidence.",
      "Install paths cover containerized use and common MCP client setup patterns.",
      "Tool value is concrete: repository search, issue triage, pull-request review, and workflow investigation.",
      "Permission risk is understandable because teams can review token scopes before connecting.",
      "Evidence confidence is high because source ownership, docs, and package distribution are all directly linkable.",
    ],
    cautions: [
      "Treat write-capable repository actions as privileged operations and separate read-only from mutation workflows.",
      "Use organization policy to limit repositories, token scopes, and approval paths for issue or pull-request mutation.",
      "Audit chat transcripts that include private code context before forwarding to third-party models.",
    ],
    examples: [
      "Summarize open pull requests before standup.",
      "Find recent issues related to a failing CI workflow.",
      "Draft a safe investigation plan for a repository incident.",
    ],
    useCases: [
      "Best fit for coding-agent workflows where repository context is the primary MCP need.",
      "Useful for support engineers who need issue and pull-request context without manually switching tools.",
      "Strong default candidate for teams building an MCP baseline because value is broad and review evidence is strong.",
    ],
    riskAnalysis: [
      "Primary risk is overbroad repository or organization token scope.",
      "Mutation tools should be gated by human approval and separated from read-only inspection.",
      "Private code exposure risk depends on the connected client and model provider, not only the MCP server.",
    ],
    maintenanceNotes: [
      "First-party repository and package ownership reduce supply-chain ambiguity.",
      "Review cadence should watch release notes, token-scope changes, and new write-capable tools.",
    ],
  }),
  server({
    slug: "filesystem",
    name: "Filesystem",
    category: "Local automation",
    tagline: "Controlled local file access for assistants running in a developer workspace.",
    source: "Model Context Protocol reference servers and client configuration docs",
    sourceLinks: [
      repo("https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem"),
      npmPackage("@modelcontextprotocol/server-filesystem"),
      registryLink,
    ],
    packageName: "@modelcontextprotocol/server-filesystem",
    installCommand: "npx -y @modelcontextprotocol/server-filesystem ./workspace",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-14",
    evidenceUpdated: "2026-05-14",
    status: "reviewed",
    confidence: "high",
    transports: ["stdio"],
    clients,
    risk: "medium",
    score: { installDocs: 88, maintenance: 84, auth: 72, compatibility: 93, usefulness: 91, safety: 73 },
    signals: ["Broad client support", "Simple install path", "Powerful local access surface", "Scope-sensitive safety profile"],
    evidence: [
      "The server is easy to install and widely referenced in MCP client setup examples.",
      "Its utility is extremely high for coding agents, document workflows, and local project inspection.",
      "Safety depends almost entirely on directory allowlists and whether sensitive folders are exposed.",
      "A restricted project-root configuration is materially different from broad home-directory access.",
      "High confidence comes from reference-server provenance and repeatable local configuration review.",
    ],
    cautions: [
      "Never expose home directories, SSH keys, cloud credentials, browser profiles, or secrets folders by default.",
      "Prefer read-only or workspace-scoped configurations when the client supports them.",
      "Treat local-file access as a privileged tool even when the server itself is simple.",
    ],
    examples: ["Read a project README before editing.", "List generated artifacts after a build.", "Inspect config files inside a scoped repository."],
    useCases: [
      "Best for developer workspaces where agents need project-local files.",
      "Useful for documentation teams reviewing generated artifacts.",
      "Not a good fit for unmanaged employee machines without a clear allowlist policy.",
    ],
    riskAnalysis: [
      "Local file access can leak secrets through prompt context if the exposed root is too broad.",
      "Workspace scoping and explicit approvals reduce risk more than any score label can.",
      "Risk increases when paired with write tools or autonomous agents.",
    ],
    maintenanceNotes: [
      "Reference-server maintenance is strong, but production readiness still depends on local client policy.",
      "Review install docs whenever client permission models change.",
    ],
  }),
  server({
    slug: "context7",
    name: "Context7",
    category: "Documentation",
    tagline: "Library documentation retrieval for coding assistants.",
    source: "Upstash repository, MCP registry, Smithery listing",
    sourceLinks: [
      repo("https://github.com/upstash/context7"),
      npmPackage("@upstash/context7-mcp"),
      { label: "Smithery listing", type: "smithery", url: "https://smithery.ai/server/@upstash/context7-mcp" },
      registryLink,
    ],
    packageName: "@upstash/context7-mcp",
    installCommand: "npx -y @upstash/context7-mcp",
    repositoryUrl: "https://github.com/upstash/context7",
    stars: 15800,
    lastReviewed: "2026-05-14",
    evidenceUpdated: "2026-05-14",
    status: "maintainer_verified",
    confidence: "high",
    maintainerVerifiedAt: "2026-05-14",
    transports: ["stdio", "sse"],
    clients: ["claude", "cursor", "codex"],
    risk: "low",
    score: { installDocs: 91, maintenance: 92, auth: 86, compatibility: 84, usefulness: 93, safety: 86 },
    signals: ["Clear developer use case", "Low data sensitivity", "High community visibility", "Strong coding-agent fit"],
    evidence: [
      "The default data surface is documentation retrieval rather than private customer or repository data.",
      "Package and repository paths are easy to verify before install.",
      "Usefulness is high for teams trying to reduce hallucinated library API usage.",
      "Auth and safety risk are lower than systems that touch local files, payments, or production databases.",
      "High confidence comes from direct source links and a repeatable install path.",
    ],
    cautions: [
      "Documentation retrieval can still produce outdated guidance if source docs lag the package version.",
      "Teams should cite retrieved docs in code review when using agent-generated implementation advice.",
    ],
    examples: ["Pull current framework docs during implementation.", "Compare library API usage before refactoring.", "Reduce stale package guidance in coding agents."],
    useCases: [
      "Best for Cursor, Claude, and Codex users who often ask agents for package-specific implementation details.",
      "Useful as a low-risk first MCP server for teams evaluating developer productivity.",
      "Pairs well with GitHub MCP when agents need both docs and repository context.",
    ],
    riskAnalysis: [
      "Main risk is answer quality, not privileged data access.",
      "Teams should verify that documentation sources match the library versions in use.",
    ],
    maintenanceNotes: ["Repository activity and package visibility should be rechecked weekly while MCP adoption is moving quickly."],
  }),
  server({
    slug: "slack-mcp",
    name: "Slack MCP Server",
    category: "Communication",
    tagline: "Workspace messages, channels, and collaboration context for team agents.",
    source: "Archived MCP reference server, Zencoder-maintained continuation, GitHub repository",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack"), registryLink],
    packageName: "@modelcontextprotocol/server-slack",
    installCommand: "npx -y @modelcontextprotocol/server-slack",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-13",
    status: "high_risk",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "high",
    score: { installDocs: 74, maintenance: 65, auth: 58, compatibility: 72, usefulness: 86, safety: 49 },
    signals: ["High collaboration value", "OAuth and workspace retention sensitivity", "Archived original reference path"],
    evidence: ["Useful for channel context and team coordination.", "Risk is high because chat history can include secrets, customer data, and personnel data.", "Original reference server path is archived, so ownership and maintenance require careful verification."],
    cautions: ["Do not call Slack one of the safest MCP servers.", "Review OAuth scopes, retention policy, and workspace approval before enabling.", "Avoid broad channel access for autonomous agents."],
    examples: ["Summarize an incident channel.", "Find context from a release discussion.", "Draft a follow-up based on a public team channel."],
  }),
  server({
    slug: "postgres",
    name: "Postgres",
    category: "Databases",
    tagline: "SQL inspection and query workflows for Postgres-backed products.",
    source: "Archived MCP reference server, package metadata, database client examples",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres"), npmPackage("@modelcontextprotocol/server-postgres"), registryLink],
    packageName: "@modelcontextprotocol/server-postgres",
    installCommand: "npx -y @modelcontextprotocol/server-postgres postgresql://...",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-13",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: { installDocs: 80, maintenance: 75, auth: 67, compatibility: 84, usefulness: 88, safety: 66 },
    signals: ["Strong analytical value", "Credential handling is deployment-specific", "Readonly roles strongly recommended"],
    evidence: ["Straightforward install for teams already using connection strings.", "Useful for schema exploration and read-only analysis.", "Safety depends on database role, network, and environment separation."],
    cautions: ["Use readonly roles and non-production replicas where possible.", "Do not give agent sessions production write credentials."],
    examples: ["Explain table relationships.", "Draft a read-only analytics query.", "Find likely PII columns."],
  }),
  server({
    slug: "stripe-mcp",
    name: "Stripe MCP Server",
    category: "Finance",
    tagline: "Payment object lookup and billing operations for Stripe-backed products.",
    source: "Stripe repository, package metadata, MCP directories",
    sourceLinks: [repo("https://github.com/stripe/agent-toolkit"), npmPackage("@stripe/mcp"), registryLink],
    packageName: "@stripe/mcp",
    installCommand: "npx -y @stripe/mcp",
    repositoryUrl: "https://github.com/stripe/agent-toolkit",
    stars: 5400,
    lastReviewed: "2026-05-13",
    status: "high_risk",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "high",
    score: { installDocs: 83, maintenance: 87, auth: 64, compatibility: 72, usefulness: 84, safety: 55 },
    signals: ["Financial data access", "Operationally useful", "Restricted API keys required"],
    evidence: ["Useful for payment debugging and billing support workflows.", "Safety score is constrained by sensitive financial data exposure.", "Restricted keys and sandbox mode are central to safe rollout."],
    cautions: ["Never allow autonomous refund or invoice mutation without approval.", "Start with sandbox mode and restricted keys."],
    examples: ["Look up a failed payment.", "Explain a subscription state.", "Draft a billing investigation checklist."],
  }),
  server({
    slug: "brave-search",
    name: "Brave Search",
    category: "Search",
    tagline: "Web search results for agents that need current public context.",
    source: "Archived MCP reference server and Brave Search API docs",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/brave-search"), npmPackage("@modelcontextprotocol/server-brave-search"), registryLink],
    packageName: "@modelcontextprotocol/server-brave-search",
    installCommand: "npx -y @modelcontextprotocol/server-brave-search",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients,
    risk: "low",
    score: { installDocs: 79, maintenance: 76, auth: 80, compatibility: 88, usefulness: 82, safety: 78 },
    signals: ["Low local data exposure", "External API key required", "Useful for current public references"],
    evidence: ["Narrow public-search surface.", "Risk mostly comes from query logging and API-key handling.", "Helpful when agents need public context."],
    cautions: ["Do not send private customer data as search queries.", "Review provider logging and retention terms."],
    examples: ["Find package docs.", "Check a public CVE reference.", "Gather market references."],
  }),
  server({
    slug: "memory",
    name: "Memory",
    category: "Local automation",
    tagline: "Persistent local knowledge graph for assistant context across sessions.",
    source: "MCP reference server and client docs",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/memory"), npmPackage("@modelcontextprotocol/server-memory"), registryLink],
    packageName: "@modelcontextprotocol/server-memory",
    installCommand: "npx -y @modelcontextprotocol/server-memory",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: { installDocs: 78, maintenance: 80, auth: 70, compatibility: 82, usefulness: 80, safety: 65 },
    signals: ["Persistent data surface", "Useful for long-running workflows", "Needs retention controls"],
    evidence: ["Persistence can improve continuity.", "Safety depends on what the assistant writes into memory.", "Best used with clear retention and deletion controls."],
    cautions: ["Avoid storing secrets or personal data.", "Give users controls to inspect and delete stored facts."],
    examples: ["Remember repo conventions.", "Track project terminology.", "Store non-sensitive workflow notes."],
  }),
  server({
    slug: "sequential-thinking",
    name: "Sequential Thinking",
    category: "Reasoning",
    tagline: "Structured problem-solving tool for stepwise decomposition and revision.",
    source: "MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking"), npmPackage("@modelcontextprotocol/server-sequential-thinking"), registryLink],
    packageName: "@modelcontextprotocol/server-sequential-thinking",
    installCommand: "npx -y @modelcontextprotocol/server-sequential-thinking",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients,
    risk: "low",
    score: score(82),
    signals: ["No external data by default", "Useful for planning", "Low credential exposure"],
    evidence: ["Reference implementation with a narrow reasoning surface.", "Does not require access to private systems by default."],
    cautions: ["Do not confuse structured reasoning with factual evidence.", "Still verify final claims against source material."],
    examples: ["Plan a migration.", "Break down debugging steps.", "Explore alternatives before implementation."],
  }),
  server({
    slug: "fetch",
    name: "Fetch",
    category: "Web retrieval",
    tagline: "Fetch and convert web content for model-readable context.",
    source: "MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/fetch"), registryLink],
    packageName: "mcp-server-fetch",
    installCommand: "uvx mcp-server-fetch",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "low",
    score: score(80),
    signals: ["Public web retrieval", "No local data surface", "Useful for source-grounded answers"],
    evidence: ["Narrow surface area and clear usefulness.", "Risk is mostly URL choice, content trust, and network policy."],
    cautions: ["Do not fetch sensitive internal URLs unless explicitly allowed.", "Treat fetched web content as untrusted input."],
    examples: ["Read public docs.", "Summarize a public changelog.", "Collect evidence links."],
  }),
  server({
    slug: "git",
    name: "Git",
    category: "Developer tools",
    tagline: "Read and inspect local Git repositories from MCP clients.",
    source: "MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/git"), registryLink],
    packageName: "mcp-server-git",
    installCommand: "uvx mcp-server-git --repository ./repo",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients,
    risk: "medium",
    score: score(79),
    signals: ["Local repository access", "Developer-useful", "Scope-sensitive"],
    evidence: ["Useful for history and diff inspection.", "Risk depends on repository scoping and write permissions."],
    cautions: ["Avoid exposing repositories containing secrets.", "Use read-only workflows unless mutation is explicitly needed."],
    examples: ["Inspect recent commits.", "Summarize a diff.", "Find who changed a file."],
  }),
  server({
    slug: "time",
    name: "Time",
    category: "Utilities",
    tagline: "Timezone conversion and current-time utilities for agents.",
    source: "MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/time"), registryLink],
    packageName: "mcp-server-time",
    installCommand: "uvx mcp-server-time",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-12",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients,
    risk: "low",
    score: score(77),
    signals: ["Tiny utility surface", "No private data needed", "Useful for scheduling"],
    evidence: ["Simple capability with minimal data exposure.", "Low operational risk when installed from known source."],
    cautions: ["Verify timezone assumptions in user-facing workflows."],
    examples: ["Convert meeting times.", "Calculate deadlines.", "Normalize timestamps."],
  }),
  server({
    slug: "notion-mcp",
    name: "Notion MCP Server",
    category: "Productivity",
    tagline: "Workspace page and database access for Notion-backed teams.",
    source: "Notion MCP repository and MCP directories",
    sourceLinks: [repo("https://github.com/makenotion/notion-mcp-server"), registryLink],
    packageName: "@notionhq/notion-mcp-server",
    installCommand: "npx -y @notionhq/notion-mcp-server",
    repositoryUrl: "https://github.com/makenotion/notion-mcp-server",
    stars: 4300,
    lastReviewed: "2026-05-11",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio", "streamable-http"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(81),
    signals: ["Workspace knowledge access", "OAuth scope review needed", "High productivity value"],
    evidence: ["Useful for internal docs and project knowledge.", "Risk depends on workspace scope and page/database permissions."],
    cautions: ["Do not grant broad workspace access without approval.", "Review whether pages include customer or HR data."],
    examples: ["Find project specs.", "Summarize a planning database.", "Draft status updates from docs."],
  }),
  server({
    slug: "browserbase",
    name: "Browserbase",
    category: "Web automation",
    tagline: "Cloud browser automation for agents that need controlled browser sessions.",
    source: "Browserbase repository and docs",
    sourceLinks: [repo("https://github.com/browserbase/mcp-server-browserbase"), docs("https://docs.browserbase.com/integrations/mcp/introduction"), registryLink],
    packageName: "@browserbasehq/mcp-server-browserbase",
    installCommand: "npx -y @browserbasehq/mcp-server-browserbase",
    repositoryUrl: "https://github.com/browserbase/mcp-server-browserbase",
    stars: 1800,
    lastReviewed: "2026-05-11",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: score(80),
    signals: ["Remote browser sessions", "Useful testing workflow", "Credential and session controls matter"],
    evidence: ["Strong fit for QA and browser inspection.", "Risk depends on session data, authenticated apps, and artifact storage."],
    cautions: ["Do not run unattended against production admin surfaces.", "Store screenshots and session artifacts according to policy."],
    examples: ["Validate signup flows.", "Capture screenshots.", "Inspect deployed pages."],
  }),
  server({
    slug: "sqlite",
    name: "SQLite",
    category: "Databases",
    tagline: "Local SQLite database inspection and lightweight analysis.",
    source: "Archived MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite"), registryLink],
    packageName: "@modelcontextprotocol/server-sqlite",
    installCommand: "npx -y @modelcontextprotocol/server-sqlite ./data.db",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(76),
    signals: ["Local data access", "Useful for small apps", "Archived reference path"],
    evidence: ["Useful for local analytics and prototyping.", "Risk depends on database contents and file scope."],
    cautions: ["Avoid databases containing secrets or regulated customer data.", "Prefer copies over live production data."],
    examples: ["Inspect local app data.", "Draft SQL queries.", "Analyze test fixtures."],
  }),
  server({
    slug: "redis",
    name: "Redis",
    category: "Databases",
    tagline: "Key-value store access for Redis-backed systems.",
    source: "Archived MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/redis"), registryLink],
    packageName: "@modelcontextprotocol/server-redis",
    installCommand: "npx -y @modelcontextprotocol/server-redis redis://localhost:6379",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(72),
    signals: ["Operational data access", "Credential handling required", "Archived reference path"],
    evidence: ["Useful for cache inspection and queue debugging.", "Confidence remains low pending current maintainer verification."],
    cautions: ["Do not connect to production Redis without strict read-only policy.", "Keys may contain session or customer data."],
    examples: ["Inspect cache keys.", "Debug queue state.", "Check TTL behavior."],
  }),
  server({
    slug: "sentry",
    name: "Sentry",
    category: "Observability",
    tagline: "Issue and error context for incident triage.",
    source: "Archived MCP reference server and Sentry ecosystem mentions",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sentry"), registryLink],
    packageName: "@modelcontextprotocol/server-sentry",
    installCommand: "npx -y @modelcontextprotocol/server-sentry",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(74),
    signals: ["Incident context", "Potential PII in stack traces", "Archived reference path"],
    evidence: ["Useful for incident summaries.", "Risk depends on issue payload content and token scope."],
    cautions: ["Stack traces may contain sensitive data.", "Scope tokens to projects and read-only operations."],
    examples: ["Summarize top errors.", "Group related incidents.", "Draft a remediation checklist."],
  }),
  server({
    slug: "google-drive",
    name: "Google Drive",
    category: "Files and storage",
    tagline: "Drive file search and retrieval for workspace documents.",
    source: "Archived MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive"), registryLink],
    packageName: "@modelcontextprotocol/server-gdrive",
    installCommand: "npx -y @modelcontextprotocol/server-gdrive",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "high_risk",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude"],
    risk: "high",
    score: score(70),
    signals: ["Workspace file access", "OAuth sensitive", "Archived reference path"],
    evidence: ["Potentially useful for document retrieval.", "High risk until scopes and current ownership are verified."],
    cautions: ["Drive often contains HR, legal, finance, and customer data.", "Do not enable broad domain-wide access."],
    examples: ["Find a public project doc.", "Summarize a shared spec.", "Locate onboarding materials."],
  }),
  server({
    slug: "linear",
    name: "Linear MCP Server",
    category: "Project management",
    tagline: "Issue, project, and roadmap workflows for Linear teams.",
    source: "Official Linear docs and MCP directories",
    sourceLinks: [docs("https://linear.app/docs/mcp"), registryLink],
    packageName: "linear-mcp",
    installCommand: "See Linear MCP docs for current install path",
    repositoryUrl: "",
    stars: 0,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "medium",
    transports: ["streamable-http"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(79),
    signals: ["First-party docs", "Project-management mutation risk", "Useful for planning workflows"],
    evidence: ["Good workflow fit for issue triage and project context.", "Risk comes from write-capable project-management actions."],
    cautions: ["Separate read-only from mutation actions.", "Review workspace permissions before enabling."],
    examples: ["Summarize open issues.", "Draft a project update.", "Find blockers in a cycle."],
  }),
  server({
    slug: "playwright-mcp",
    name: "Playwright MCP",
    category: "Web automation",
    tagline: "Browser automation backed by Playwright for testing and inspection.",
    source: "Microsoft Playwright MCP repository",
    sourceLinks: [repo("https://github.com/microsoft/playwright-mcp"), npmPackage("@playwright/mcp"), registryLink],
    packageName: "@playwright/mcp",
    installCommand: "npx -y @playwright/mcp",
    repositoryUrl: "https://github.com/microsoft/playwright-mcp",
    stars: 18800,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: score(82),
    signals: ["Known automation engine", "High testing value", "Authenticated-browser risk"],
    evidence: ["Strong fit for UI verification.", "Browser automation can interact with sensitive authenticated sessions."],
    cautions: ["Use dedicated test accounts.", "Avoid production admin sessions unless explicitly approved."],
    examples: ["Run a smoke test.", "Inspect accessibility tree.", "Capture a visual regression."],
  }),
  server({
    slug: "puppeteer",
    name: "Puppeteer",
    category: "Web automation",
    tagline: "Browser automation and web scraping via an archived MCP reference server.",
    source: "Archived MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer"), npmPackage("@modelcontextprotocol/server-puppeteer"), registryLink],
    packageName: "@modelcontextprotocol/server-puppeteer",
    installCommand: "npx -y @modelcontextprotocol/server-puppeteer",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(73),
    signals: ["Useful automation surface", "Archived reference path", "Potential scraping policy concerns"],
    evidence: ["Browser automation is useful but needs active ownership review.", "Confidence remains low until maintained alternative is verified."],
    cautions: ["Respect site terms and robots policy.", "Use test credentials for authenticated sessions."],
    examples: ["Capture a screenshot.", "Inspect page content.", "Test a simple flow."],
  }),
  server({
    slug: "google-maps",
    name: "Google Maps",
    category: "Location",
    tagline: "Places, directions, and location lookup for map-aware agents.",
    source: "Archived MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps"), npmPackage("@modelcontextprotocol/server-google-maps"), registryLink],
    packageName: "@modelcontextprotocol/server-google-maps",
    installCommand: "npx -y @modelcontextprotocol/server-google-maps",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude"],
    risk: "low",
    score: score(71),
    signals: ["External API key", "Low local data exposure", "Archived reference path"],
    evidence: ["Useful for public location lookups.", "Confidence is low pending current ownership and install verification."],
    cautions: ["Do not send sensitive customer location data without policy review.", "Monitor API key usage and spend."],
    examples: ["Find nearby services.", "Estimate travel distance.", "Resolve place details."],
  }),
  server({
    slug: "gitlab",
    name: "GitLab",
    category: "Developer tools",
    tagline: "GitLab project, issue, and merge-request workflows for agents.",
    source: "Archived MCP reference server and GitLab API docs",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gitlab"), npmPackage("@modelcontextprotocol/server-gitlab"), registryLink],
    packageName: "@modelcontextprotocol/server-gitlab",
    installCommand: "npx -y @modelcontextprotocol/server-gitlab",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers-archived",
    stars: 85600,
    lastReviewed: "2026-05-10",
    status: "reviewed",
    confidence: "low",
    transports: ["stdio"],
    clients: ["claude", "cursor"],
    risk: "medium",
    score: score(72),
    signals: ["Code-hosting access", "Token scope sensitive", "Archived reference path"],
    evidence: ["Useful for teams on GitLab.", "Low confidence because current maintenance path needs verification."],
    cautions: ["Use least-privilege tokens.", "Review write-capable operations separately."],
    examples: ["Find merge requests.", "Summarize an issue.", "Inspect CI status."],
  }),
  server({
    slug: "everything",
    name: "Everything",
    category: "Reference",
    tagline: "Reference and test server that exercises MCP prompts, resources, and tools.",
    source: "MCP reference server",
    sourceLinks: [repo("https://github.com/modelcontextprotocol/servers/tree/main/src/everything"), npmPackage("@modelcontextprotocol/server-everything"), registryLink],
    packageName: "@modelcontextprotocol/server-everything",
    installCommand: "npx -y @modelcontextprotocol/server-everything",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 85600,
    lastReviewed: "2026-05-09",
    status: "reviewed",
    confidence: "medium",
    transports: ["stdio"],
    clients,
    risk: "low",
    score: score(70),
    signals: ["Reference/testing utility", "Not production-purpose specific", "Good client smoke test"],
    evidence: ["Useful for testing MCP client compatibility.", "Not intended as a production workflow tool."],
    cautions: ["Do not rank as a business-useful server despite low risk.", "Use for test harnesses and client validation."],
    examples: ["Validate MCP client setup.", "Exercise prompts/resources/tools.", "Debug protocol behavior."],
  }),
];

const indexedSeeds: Array<{
  slug: string;
  name: string;
  category: string;
  tagline: string;
  sourceUrl?: string;
  repositoryUrl?: string;
  packageName?: string;
  installCommand?: string;
  risk?: RiskLevel;
  source?: string;
}> = [
  { slug: "inference-sh", name: "inference.sh", category: "AI tools", tagline: "Run AI apps for image, video, audio, LLM, and 3D generation.", sourceUrl: "https://sh.inference.ac", risk: "medium" },
  { slug: "tandem-docs-mcp", name: "Tandem Docs MCP", category: "Documentation", tagline: "Remote MCP server for Tandem docs, SDKs, workflows, and agent setup help.", repositoryUrl: "https://github.com/frumu-ai/tandem", sourceUrl: "https://tandem.ac/mcp" },
  { slug: "lona-trading", name: "Lona Trading", category: "Finance", tagline: "Trading strategy development, backtesting, market data, and portfolio analysis.", repositoryUrl: "https://github.com/mindsightventures/lona", sourceUrl: "https://mcp.lona.agency/mcp", risk: "high" },
  { slug: "atars-mcp", name: "aTars MCP", category: "Finance", tagline: "Crypto market signals, technical indicators, and sentiment analysis.", sourceUrl: "https://mcp.aarna.ai/mcp", risk: "high" },
  { slug: "abmeter", name: "ABMeter", category: "Analytics", tagline: "Feature flagging and A/B testing platform workflows.", repositoryUrl: "https://github.com/abmeter/abmeter", sourceUrl: "https://mcp.abmeter.ai" },
  { slug: "adadvisor-mcp", name: "AdAdvisor MCP", category: "Marketing", tagline: "Query Meta Ads account, campaign, ad set, ad, metrics, and settings data.", sourceUrl: "https://api.adadvisor.ai/mcp", risk: "high" },
  { slug: "adeu", name: "ADeu", category: "Documents", tagline: "Automated DOCX redlining engine for deal and legal workflows.", repositoryUrl: "https://github.com/dealfluence/adeu", risk: "medium" },
  { slug: "adramp-google-ads", name: "AdRamp Google Ads", category: "Marketing", tagline: "Manage Google Ads campaigns, keywords, and metrics.", sourceUrl: "https://mcp.adramp.ai", risk: "high" },
  { slug: "adweave-meta-ads", name: "AdWeave Meta Ads", category: "Marketing", tagline: "Meta Ads tools for campaigns, creatives, audiences, and insights.", sourceUrl: "https://mcp.adweave.ai/meta-ads-mcp", risk: "high" },
  { slug: "agentdm", name: "AgentDM", category: "Communication", tagline: "Agent-to-agent messages, channels, and skill communication.", repositoryUrl: "https://github.com/agentdmai/agentdm", sourceUrl: "https://api.agentdm.ai/mcp/v1/grid" },
  { slug: "agentic-news", name: "Agentic News", category: "News", tagline: "Personalized monitoring, briefings, and semantic news search.", repositoryUrl: "https://github.com/u00dxk2/agentic-news", sourceUrl: "https://api.agentic-news.ai/mcp" },
  { slug: "agentic-shelf", name: "Agentic Shelf", category: "Commerce", tagline: "Hosted e-commerce catalog, stock, and pricing for agents.", repositoryUrl: "https://github.com/vboykoCTO/agentic-shelf", sourceUrl: "https://api.agenticshelf.ai/mcp" },
  { slug: "agentrapay-agentra", name: "Agentra", category: "Identity", tagline: "Identity oracle and trust scoring for autonomous agents.", sourceUrl: "https://api.agentrapay.ai/mcp", risk: "medium" },
  { slug: "agenttrust", name: "AgentTrust", category: "Identity", tagline: "Identity, trust, and A2A orchestration for autonomous agents.", repositoryUrl: "https://github.com/agenttrust/mcp-server" },
  { slug: "spotdb", name: "SpotDB", category: "Data", tagline: "Ephemeral data sandbox for AI workflows with guardrails.", repositoryUrl: "https://github.com/aliengiraffe/spotdb" },
  { slug: "alpic", name: "Alpic", category: "Developer tools", tagline: "Manage projects, debug deployment, and check analytics for hosted MCP servers.", sourceUrl: "https://mcp.alpic.ai" },
  { slug: "anki-mcp-server", name: "Anki MCP Server", category: "Education", tagline: "Adaptive review, notes, media, and deck management through AnkiConnect.", repositoryUrl: "https://github.com/ankimcp/anki-mcp-server" },
  { slug: "anomalyarmor", name: "AnomalyArmor", category: "Observability", tagline: "Data observability alerts, freshness, schema drift, lineage, and quality.", repositoryUrl: "https://github.com/anomalyarmor/agents", sourceUrl: "https://mcp.anomalyarmor.ai/mcp" },
  { slug: "appdeploy", name: "AppDeploy", category: "Deployment", tagline: "Turns app ideas from AI chat into live full-stack web apps.", sourceUrl: "https://api-v2.appdeploy.ai/mcp", risk: "medium" },
  { slug: "artidrop", name: "ArtiDrop", category: "Publishing", tagline: "Publish HTML, Markdown, and multi-file sites as shareable URLs.", sourceUrl: "https://artidrop.ai/mcp" },
  { slug: "auteng-docs", name: "AutEng Docs", category: "Publishing", tagline: "Publish markdown documents as public share links with Mermaid diagrams.", sourceUrl: "https://auteng.ai/mcp/docs" },
  { slug: "contextlayer", name: "ContextLayer", category: "Memory", tagline: "Personal context management for AI assistants.", repositoryUrl: "https://github.com/autoblocksai/ctxl" },
  { slug: "autonomad-travel", name: "Autonomad Travel", category: "Travel", tagline: "Book flights, hotels, activities, and events worldwide.", repositoryUrl: "https://github.com/Autonomad1/autonomad1", sourceUrl: "https://mcp.autonomad.ai/mcp", risk: "high" },
  { slug: "auxen", name: "Auxen", category: "AI infrastructure", tagline: "Provision private AI model endpoints on dedicated GPUs.", repositoryUrl: "https://github.com/auxen-ai/auxen-mcp", sourceUrl: "https://api.auxen.ai/mcp" },
  { slug: "inferventis", name: "Inferventis", category: "Finance", tagline: "Loan, mortgage, compound interest, ROI, crypto, and FX calculators.", repositoryUrl: "https://github.com/Bankee-ai/inferventis", sourceUrl: "https://mcp-server-295985738387.europe-west1.run.app/mcp", risk: "medium" },
  { slug: "baselight", name: "Baselight", category: "Data", tagline: "Query a public catalog of datasets for finance, demographics, sports, and more.", sourceUrl: "https://api.baselight.app/mcp" },
  { slug: "bezal-local-commerce", name: "Bezal Local Commerce", category: "Commerce", tagline: "Search local service businesses by category, location, or keyword.", sourceUrl: "https://app.bezal.ai/api/mcp" },
  { slug: "bluenexus-universal", name: "BlueNexus Universal MCP", category: "Data integration", tagline: "Connect agents to many data sources with compliance-aware filtering.", sourceUrl: "https://api.bluenexus.ai/mcp", risk: "high" },
  { slug: "borealhost", name: "BorealHost", category: "Deployment", tagline: "Agent-native web hosting, DNS, domain, and infrastructure management.", repositoryUrl: "https://github.com/alainsvrd/borealhost-mcp", sourceUrl: "https://borealhost.ai/mcp/" },
  { slug: "bring-your-ai", name: "Bring Your AI", category: "Developer tools", tagline: "No-data MCP handoff between local Claude Code and Codex harness moves.", sourceUrl: "https://bringyour.ai/mcp" },
  { slug: "buyersense", name: "BuyerSense", category: "Sales", tagline: "Buyer signals from any MCP client.", sourceUrl: "https://mcp.buyersense.ai/mcp" },
  { slug: "buywhere-mcp", name: "BuyWhere MCP", category: "Commerce", tagline: "Product search, price comparison, and shopping across retailers.", repositoryUrl: "https://github.com/BuyWhere/buywhere-mcp" },
  { slug: "byteray", name: "ByteRay AI", category: "Security", tagline: "Binary analysis and zero-day hunting tools for agents.", sourceUrl: "https://mcp.byteray.ai/mcp", risk: "high" },
  { slug: "childadhd-library", name: "Child ADHD Library", category: "Healthcare", tagline: "Clinician-reviewed library on ADHD evaluation, treatment, school, and parenting.", sourceUrl: "https://childadhd.ai/api/mcp/v1", risk: "high" },
  { slug: "childanxiety-library", name: "Child Anxiety Library", category: "Healthcare", tagline: "Clinician-reviewed library on anxiety, OCD, and phobias in children.", sourceUrl: "https://childanxiety.ai/api/mcp/v1", risk: "high" },
  { slug: "exa-search", name: "Exa Search", category: "Search", tagline: "Neural web search for research agents.", repositoryUrl: "https://github.com/exa-labs/exa-mcp-server", packageName: "exa-mcp-server", installCommand: "npx -y exa-mcp-server" },
  { slug: "firecrawl", name: "Firecrawl", category: "Web retrieval", tagline: "Crawl and extract web pages for agent workflows.", repositoryUrl: "https://github.com/mendableai/firecrawl-mcp-server", packageName: "firecrawl-mcp", installCommand: "npx -y firecrawl-mcp" },
  { slug: "vercel-mcp-adapter", name: "Vercel MCP Adapter", category: "Frameworks", tagline: "Adapter for serving MCP from web frameworks and serverless apps.", repositoryUrl: "https://github.com/vercel/mcp-adapter", packageName: "@vercel/mcp-adapter", installCommand: "npm install @vercel/mcp-adapter" },
  { slug: "mcp-guardian", name: "MCP Guardian", category: "Security", tagline: "Proxy and control surface for managing MCP server access.", repositoryUrl: "https://github.com/EQTYLab/mcp-guardian" },
  { slug: "mcp-proxy", name: "MCPProxy", category: "Infrastructure", tagline: "Local proxy for multiple MCP servers with discovery and quarantine features.", repositoryUrl: "https://github.com/sparfenyuk/mcp-proxy" },
  { slug: "mcp-router", name: "MCP Router", category: "Infrastructure", tagline: "Desktop MCP management, authentication, and log visualization.", sourceUrl: "https://mcp-router.net" },
  { slug: "mcp-run", name: "mcp.run", category: "Infrastructure", tagline: "Hosted registry and control plane for running portable MCP servers.", sourceUrl: "https://mcp.run" },
  { slug: "mcp-manager", name: "MCP Manager", category: "Infrastructure", tagline: "Simple web UI to install and manage MCP servers.", repositoryUrl: "https://github.com/Zue/mcp-manager" },
  { slug: "fastmcp", name: "FastMCP", category: "Frameworks", tagline: "Framework for building MCP servers quickly.", repositoryUrl: "https://github.com/jlowin/fastmcp", packageName: "fastmcp", installCommand: "pip install fastmcp" },
  { slug: "spring-ai-mcp", name: "Spring AI MCP", category: "Frameworks", tagline: "Spring Boot auto-configuration for MCP server and client functionality.", sourceUrl: "https://docs.spring.io/spring-ai/reference/api/mcp/mcp-overview.html" },
];

const indexedServers = indexedSeeds.map((item) =>
  server({
    slug: item.slug,
    name: item.name,
    category: item.category,
    tagline: item.tagline,
    source: item.source ?? "Official MCP registry and public source links",
    sourceLinks: [
      ...(item.repositoryUrl ? [repo(item.repositoryUrl)] : []),
      ...(item.packageName?.startsWith("@") || item.packageName?.includes("mcp") ? [npmPackage(item.packageName)] : []),
      ...(item.sourceUrl ? [{ label: "Provider MCP endpoint or docs", type: "website" as const, url: item.sourceUrl }] : []),
      registryLink,
    ],
    packageName: item.packageName ?? "",
    installCommand: item.installCommand ?? "Review provider documentation before install",
    repositoryUrl: item.repositoryUrl ?? "",
    stars: 0,
    lastReviewed: "",
    evidenceUpdated: "2026-05-14",
    status: "indexed" as ReviewStatus,
    confidence: "low" as ConfidenceLevel,
    transports: item.sourceUrl ? ["streamable-http"] : ["stdio"],
    clients: ["claude", "cursor"],
    risk: item.risk ?? "medium",
    score: { installDocs: 0, maintenance: 0, auth: 0, compatibility: 0, usefulness: 0, safety: 0 },
    signals: ["Indexed from public MCP sources", "Not yet manually reviewed", "Excluded from trusted rankings"],
    evidence: ["MCP Rank has indexed this server but has not completed a manual trust review yet."],
    cautions: ["Do not treat this indexed listing as a recommendation.", "Submit or claim the listing to improve evidence quality."],
    examples: ["Review source links.", "Check maintainer identity.", "Verify install and auth behavior before rollout."],
  }),
);

export const servers: McpServer[] = [...reviewedServers, ...indexedServers];

export const weeklyReports: WeeklyReport[] = [
  {
    slug: "weekly-best-mcp-service",
    title: "MCP Trust Report: GitHub Leads, Filesystem Needs Scoping",
    weekOf: "2026-05-14",
    winnerSlug: "github-mcp-server",
    summary:
      "GitHub MCP Server leads this week because it combines first-party provenance, broad developer usefulness, and reviewable permission boundaries. The larger signal: teams should treat MCP installation as a security decision, not a directory browse.",
    whyItWon: [
      "First-party publisher and clear repository/package provenance.",
      "High-value developer workflows across repository search, issue triage, and pull-request review.",
      "Permission risk is manageable when teams pin repository scopes and separate read-only from write-capable actions.",
    ],
    watchList: [
      "Filesystem remains essential but depends on strict path scoping.",
      "Context7 is a strong low-risk documentation candidate for coding teams.",
      "Slack and Stripe are high-utility but high-risk until OAuth scopes and mutation controls are verified.",
    ],
    biggestRiskNote:
      "High-utility servers increasingly touch sensitive systems: payments, chat history, local files, databases, and browser sessions. MCP Rank will not include those servers in safest lists unless confidence is medium/high and the risk surface is explicit.",
    newlyIndexed: indexedSeeds.slice(0, 8).map((item) => item.name),
    needsVerification: ["Slack MCP Server", "Stripe MCP Server", "Google Drive", "Redis", "Sentry"],
    changes: [
      "Expanded the indexed dataset beyond 50 public MCP servers.",
      "Promoted GitHub, Filesystem, and Context7 to high-confidence deep reviews.",
      "Separated indexed listings from trusted rankings so unreviewed tools do not inflate leaderboard trust.",
    ],
  },
];
