import type { McpServer, WeeklyReport } from "./types";

export const servers: McpServer[] = [
  {
    slug: "github-mcp-server",
    name: "GitHub MCP Server",
    category: "Developer tools",
    tagline: "Repository, issue, pull request, and code search workflows for agentic coding.",
    source: "Official MCP registry, GitHub search",
    packageName: "github/github-mcp-server",
    installCommand: "docker run -i --rm ghcr.io/github/github-mcp-server",
    repositoryUrl: "https://github.com/github/github-mcp-server",
    stars: 24700,
    lastReviewed: "2026-05-09",
    transports: ["stdio", "streamable-http"],
    clients: ["claude", "cursor", "codex", "vscode"],
    risk: "low",
    score: {
      installDocs: 91,
      maintenance: 94,
      auth: 88,
      compatibility: 93,
      usefulness: 96,
      safety: 86,
    },
    signals: [
      "First-party publisher",
      "Active issue and release activity",
      "Clear token scope guidance",
      "High-value daily developer workflow",
    ],
    evidence: [
      "Installation path is documented for Docker and local clients.",
      "OAuth and token handling are explicit enough to review before install.",
      "Common workflows map cleanly to code review and issue triage use cases.",
    ],
    cautions: [
      "Teams should pin allowed repository scopes before enabling write actions.",
      "Review organization policy for issue and pull-request mutation tools.",
    ],
    examples: [
      "Summarize open pull requests before standup.",
      "Find recent issues related to a failing CI workflow.",
      "Create a draft issue from a debugging transcript.",
    ],
  },
  {
    slug: "filesystem",
    name: "Filesystem",
    category: "Local automation",
    tagline: "Controlled local file access for assistants running in a developer workspace.",
    source: "Official MCP examples, client docs",
    packageName: "@modelcontextprotocol/server-filesystem",
    installCommand: "npx -y @modelcontextprotocol/server-filesystem ./workspace",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex", "vscode"],
    risk: "medium",
    score: {
      installDocs: 86,
      maintenance: 82,
      auth: 72,
      compatibility: 92,
      usefulness: 89,
      safety: 71,
    },
    signals: [
      "Broad client support",
      "Simple install path",
      "Powerful local access surface",
      "Needs tight path scoping",
    ],
    evidence: [
      "The server is easy to install and widely referenced in client setup guides.",
      "Usefulness is high for local coding agents and document workflows.",
      "Risk depends heavily on the root directories exposed to the MCP client.",
    ],
    cautions: [
      "Never expose home directories or secrets folders by default.",
      "Prefer read-only or workspace-scoped configurations when possible.",
    ],
    examples: [
      "Read a project README before editing.",
      "List generated artifacts after a build.",
      "Inspect a local configuration file with explicit user approval.",
    ],
  },
  {
    slug: "postgres",
    name: "Postgres",
    category: "Databases",
    tagline: "SQL inspection and query workflows for Postgres-backed products.",
    source: "Official MCP examples, Smithery, GitHub search",
    packageName: "@modelcontextprotocol/server-postgres",
    installCommand: "npx -y @modelcontextprotocol/server-postgres postgresql://...",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "medium",
    score: {
      installDocs: 80,
      maintenance: 79,
      auth: 68,
      compatibility: 84,
      usefulness: 87,
      safety: 66,
    },
    signals: [
      "Strong analytical value",
      "Credential handling is deployment-specific",
      "Readonly roles strongly recommended",
      "Can expose sensitive production data",
    ],
    evidence: [
      "The install path is straightforward for teams already using connection strings.",
      "Quality depends on database role scoping and environment separation.",
      "Useful for schema exploration, query drafting, and product analytics.",
    ],
    cautions: [
      "Use a readonly role and replica where practical.",
      "Do not give agent sessions access to production write credentials.",
    ],
    examples: [
      "Explain table relationships before building a feature.",
      "Draft a read-only analytics query.",
      "Find columns likely to contain customer-identifying data.",
    ],
  },
  {
    slug: "context7",
    name: "Context7",
    category: "Documentation",
    tagline: "Library documentation retrieval for coding assistants.",
    source: "Smithery, GitHub search, community mentions",
    packageName: "@upstash/context7-mcp",
    installCommand: "npx -y @upstash/context7-mcp",
    repositoryUrl: "https://github.com/upstash/context7",
    stars: 15800,
    lastReviewed: "2026-05-09",
    transports: ["stdio", "sse"],
    clients: ["claude", "cursor", "codex"],
    risk: "low",
    score: {
      installDocs: 88,
      maintenance: 90,
      auth: 84,
      compatibility: 82,
      usefulness: 91,
      safety: 83,
    },
    signals: [
      "Clear developer use case",
      "Low data sensitivity by default",
      "High community visibility",
      "Good fit for coding-agent workflows",
    ],
    evidence: [
      "The value proposition is narrow and easy to validate during install tests.",
      "Documentation retrieval does not require broad local or account privileges.",
      "Community mentions show recurring usage in coding-assistant setup guides.",
    ],
    cautions: [
      "Check source freshness for fast-moving frameworks.",
      "Teams with private docs still need a separate access review.",
    ],
    examples: [
      "Fetch current framework docs while editing a component.",
      "Compare API signatures across package versions.",
      "Reduce hallucinated library usage in code generation.",
    ],
  },
  {
    slug: "slack-mcp",
    name: "Slack MCP Server",
    category: "Collaboration",
    tagline: "Channel search, message context, and reply drafting for team workflows.",
    source: "Smithery, Glama, GitHub search",
    packageName: "@modelcontextprotocol/server-slack",
    installCommand: "npx -y @modelcontextprotocol/server-slack",
    repositoryUrl: "https://github.com/modelcontextprotocol/servers",
    stars: 70200,
    lastReviewed: "2026-05-09",
    transports: ["stdio"],
    clients: ["claude", "cursor", "codex"],
    risk: "high",
    score: {
      installDocs: 74,
      maintenance: 78,
      auth: 61,
      compatibility: 76,
      usefulness: 82,
      safety: 58,
    },
    signals: [
      "Useful operational context",
      "Sensitive workspace data surface",
      "OAuth scopes must be inspected",
      "Write actions require policy controls",
    ],
    evidence: [
      "The workflow value is clear for incident review and team memory.",
      "Security score is lower until OAuth scopes and retention handling are reviewed.",
      "Best used with channel allowlists and read/write separation.",
    ],
    cautions: [
      "Avoid broad workspace read scopes for default installs.",
      "Require user confirmation before posting or editing messages.",
    ],
    examples: [
      "Summarize a project channel for a daily digest.",
      "Find recent messages about a production incident.",
      "Draft a reply using thread context.",
    ],
  },
];

export const weeklyReports: WeeklyReport[] = [
  {
    slug: "weekly-best-mcp-service",
    title: "Best MCP Service This Week",
    weekOf: "2026-05-09",
    winnerSlug: "github-mcp-server",
    summary:
      "GitHub MCP Server leads this first manual review because it combines a high-utility developer workflow with first-party maintenance signals and a security posture teams can reason about before install.",
    whyItWon: [
      "Clear install path and strong first-party ownership.",
      "Practical value shows up immediately in code review, issue triage, and repository search.",
      "Auth risk is manageable when teams pin scopes and separate read from write actions.",
    ],
    watchList: [
      "Filesystem remains essential, but its trust score depends on path scoping.",
      "Context7 is a strong low-risk documentation candidate for coding teams.",
      "Slack is useful but needs deeper OAuth and workspace-retention review before recommendation.",
    ],
  },
];
